apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: jovan99djokic/hello-go:latest
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
