# k8s/hello-go-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-go
spec:
  type: NodePort
  selector:
    app: hello-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 30007
